### ISSUE TITLE
Is there any English version ?

### ISSUE THREAD

**Issue by bvbistheboss** [thefinalcutbg/DinoDent#3]
Or only Bulgarian ?

**Comment by thefinalcutbg** [comment]
Only Bulgarian. The software is tightly integrated with the APIs of Ministry of Health and  National Health Insurance Fund. However if you are software developer, you can strip away the unnecessary parts and make your own version by using the source code.
________________________________
From: bvbistheboss ***@***.***>
Sent: Wednesday, April 24, 2024 12:54
To: thefinalcutbg/DinoDent ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [thefinalcutbg/DinoDent] Is there any English version ? (Issue #3)


Or only Bulgarian ?

**Comment by thefinalcutbg** [comment]
https://github.com/thefinalcutbg/QDento

There you go :)
